=== YauheniVezhnavets/TaskFour/src/main/resources/medicines.xsd
<?xml version= "1.0" encoding= "UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"  targetNamespace="http://www.example.com/medicines"
        xmlns:tns="http://www.example.com/medicines" elementFormDefault="qualified">
    
    <element name="medicine" type="tns:Medicine" abstract="true"></element>
    <element name="pill" type="tns:Pill" substitutionGroup="tns:medicine"></element>
    <element name="syrup" type="tns:Syrup" substitutionGroup="tns:medicine"></element>
    <element name="flavored-syrup" type="tns:FlavoredSyrup" substitutionGroup="tns:syrup"></element>

    <element name="medicines">
        <complexType>
            <sequence>
                <element ref="tns:medicine" minOccurs="2" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="Medicine">
        <sequence>
            <element name="name" type="string"/>
            <element name="medicine-group" type="tns:MedicineGroup"/>
            <element name="shelf-life" type="positiveInteger"/>
        </sequence>
    </complexType>
    <complexType name="Pill">
        <complexContent>
            <extension base="tns:Medicine">
                <sequence>
                    <element name="dosage-milligrams" type="positiveInteger"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="Syrup">
        <complexContent>
            <extension base="tns:Medicine">
                <sequence>
                    <element name="volume-milliliters" type="positiveInteger"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="FlavoredSyrup">
        <complexContent>
            <extension base="tns:Syrup">
                <sequence>
                    <element name="flavoring-type" type="tns:FlavoringType"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <simpleType name="MedicineGroup">
        <restriction base="string">
            <enumeration value="VITAMINS"/>
            <enumeration value="ANTIBIOTICS"/>
            <enumeration value="PAIN_RELIVERS"/>
        </restriction>
    </simpleType>
    <simpleType name="FlavoringType">
        <restriction base="string">
            <enumeration value="LIME"/>
            <enumeration value="CHERRY"/>
            <enumeration value="APPLE"/>
            <enumeration value="ORANGE"/>
        </restriction>
    </simpleType>
</schema>

=== YauheniVezhnavets/TaskFour/target/classes/medicines.xml
<?xml version="1.0" encoding="UTF-8" ?>
<medicines
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.example.com/medicines"
        xsi:schemaLocation="http://www.example.com/medicines medicines.xsd">


    <pill>
        <name>Ibuclin</name>
        <medicine-group>ANTIBIOTICS</medicine-group>
        <shelf-life>5</shelf-life>
        <dosage-milligrams>10</dosage-milligrams>
    </pill>
    <syrup>
        <name>Pikovit</name>
        <medicine-group>VITAMINS</medicine-group>
        <shelf-life>2</shelf-life>
        <volume-milliliters>200</volume-milliliters>
    </syrup>
    <flavored-syrup>
        <name>Doctor Mom</name>
        <medicine-group>PAIN_RELIVERS</medicine-group>
        <shelf-life>2</shelf-life>
        <volume-milliliters>200</volume-milliliters>
        <flavoring-type>LIME</flavoring-type>
    </flavored-syrup>
</medicines>
